### ISSUE TITLE
htmlcomb 无法正确识别指令中的大于号

### ISSUE THREAD

**Issue by banrikun** [fengyuanchen/htmlcomb#1]
以 Vue.js 为例，假设在指令中判断服务端返回数组的长度，若大于0，则显示菜单：

``
<div class="wxm-wrapper" v-show="pointList.length > 0">
``

其中包含的`>`号被 htmlcomb 识别为 HTML 标签结尾，变成：

``
<div class="wxm-wrapper" length pointList v-show> 0">
``

求帮忙解决~谢谢~

**Comment by fengyuanchen** [comment]
Escape `>` to`&gt;`
