### ISSUE TITLE
Ordering of attributes starting by 'x' like 'ng-' and 'data-'

### ISSUE THREAD

**Issue by fabm22** [fengyuanchen/htmlcomb#2]
Hi there, 

if in order of attributes i put something lik " ng-\* " ..would all associated attributes starting by ng-  (angularjs apps) be sorted at this place ?

Also, do you deal with data- attributes  since in html5  data-ng-click is absolutely the same as ng-click only ?

Thanks for clarification

**Comment by fengyuanchen** [comment]
Just use the `ng` without `-*`:
```js
new HTMLComb({
  order: [
    'ng',
    'data-click',
    'data-ng-click'
  ]
});
```
